services:
  nodejs-app:
    image: 634713741494.dkr.ecr.us-east-1.amazonaws.com/resume-images:latest
    container_name: nodejsserver
    hostname: nodejsserver
    ports: 
      - "3000:3000"
    networks:
      - example-net
    working_dir: /app  # Set the working directory to /app
    command: npm start  # Specify the default command to run your Node.js app
    # Include the following lines to copy package.json and package-lock.json
    # into the image during the build process
    build:
      context: .
      dockerfile: nodedocker_app/dockerfile  # Update with your actual Dockerfile location

    nginx:
        build:
            context: ./nginx
        container_name: nginx
        hostname: nginx
        ports:
            - "80:80"
        depends_on:
            - nodejs-app
        networks:
            - example-net

networks:
    example-net:
        external: true  