version: '3'

services:
  nodejs-app:
    image: 634713741494.dkr.ecr.us-east-1.amazonaws.com/resume-images:latest
    container_name: nodejsserver
    hostname: nodejsserver
    ports: 
      - "3000:3000"
    networks:
      - example-net
    working_dir: /app
    command: npm start

  nginx:
    build:
      context: ./nginx
    container_name: nginx
    hostname: nginx
    ports:
      - "80:80"
    depends_on:
      - nodejs-app
    networks:
      - example-net

networks:
  example-net:
    external: true
