# Use an official Node.js runtime as a parent image
FROM node:14

# Set the working directory to /app
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./app

# Install app dependencies
RUN npm install

# Copy the rest of the application code
COPY . .

# Define environment variable
ENV API_URL=http://localhost:3001

# Run the application
CMD ["npm", "start"]