server {
  listen 80; # Listen on port 80
  server_name ymoraes.com; # Adjust if needed for a custom domain name

  location / {
    proxy_pass http://172.18.0.2:3000; # Replace with actual container name
    proxy_set_header Host $host;
    proxy_set_header X-Real-IP $remote_addr;
  }
}
~
