name: Push-to-EC2
on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to EC2
    runs-on: ubuntu-latest
  
    steps:
    - name: Checkout the files
      uses: actions/checkout@v3
  
  #testing with secrets
  #Just testing
    - name: create file
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.AWS_SERVER }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.BERNARD_SSH_KEY }}
        port: "22"
        script: | 
          echo "This is a new file created by GitHub Actions" > /home/bernard/we_love_Felipe_2.txt